### ISSUE TITLE
Does it run on ARM Android?

### ISSUE THREAD

**Issue by JerryI** [your-diary/Install-Wolfram-Engine-on-Arch-Linux-ARM#1]
Just a question. I tried many different ways of installing this on ARM64 android phone, but it faced an endless list of errors ([link](https://stackoverflow.com/questions/71281373/running-wolfram-engine-on-android-aarch64)). Have you tried to run it on some similar devices?

**Comment by your-diary** [comment]
@JerryI 

I've never tried that.

My intuition is the errors are due to the fact that Android is not GNU/Linux.
(ref: [*Android and Users' Freedom - GNU Project*](https://www.gnu.org/philosophy/android-and-users-freedom.en.html))

**Comment by JerryI** [comment]
Thanks for the link. 
Heh, i guess there is no way on how to make a sort of grid calculations using 10-100 old android smartphones ;(

**Comment by your-diary** [comment]
@JerryI 
Just for curiosity, have you tried GNU/Linux for smartphones (like [Ubuntu Touch](https://ubuntu-touch.io/))?

**Comment by JerryI** [comment]
This is actually a good idea, but then a root access needs to be unlocked, I was wondering if it is possible to do on a "virgin" phone. I've never tried, but I had a luck with Nexus 5 with [Maru OS ](https://maruos.com) installed. Wolframscript was working great, but GUI did not manage to start.
